#!/usr/bin/env bash
# display:
#To infinity and beyond indefinitely
#and sleep 2 in between each iteration

trap "echo I am invincible!!!" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
